import type { Config } from 'tailwindcss';
import plugin from 'tailwindcss/plugin';

/* El plugin solo define estructura y forma (layout, tamaños, radios).
   El color, las superficies y las sombras viven en los tokens de app/globals.css
   (:root y html[data-theme='dark']). */
const cardBorder = '1px solid var(--border)';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        ink: '#15213a',
        brand: { 500: '#2563eb', 600: '#1d4ed8' },
      },
    },
  },
  plugins: [
    plugin(({ addBase, addComponents }) => {
      addBase({
        body: {
          margin: '0',
          minHeight: '100vh',
          background: 'var(--page-bg)',
          color: 'var(--text)',
        },
        'button, input, select, textarea': { font: 'inherit' },
        button: { cursor: 'pointer' },
      });

      addComponents({
        '.app-shell': { minHeight: '100vh'},
        '.desktop-sidebar': {
          position: 'fixed',
          inset: '0 auto 0 0',
          zIndex: '35',
          display: 'none',
          width: '232px',
          overflow: 'hidden',
          border: '0',
          borderRight: cardBorder,
          borderRadius: '0 18px 18px 0',
          background: 'var(--surface)',
        },
        '.sidebar-brand': {
          display: 'flex',
          minHeight: '67px',
          alignItems: 'center',
          gap: '10px',
          borderBottom: cardBorder,
          padding: '0 15px',
        },
        '.sidebar-brand strong, .sidebar-brand small': { display: 'block' },
        '.sidebar-brand strong': {
          color: 'var(--text)',
          fontSize: '13px',
          fontWeight: '600',
          textTransform: 'uppercase',
        },
        '.sidebar-brand small': { marginTop: '2px', color: 'var(--text-muted)', fontSize: '10px' },
        '.sidebar-logo': {
          display: 'grid',
          height: '38px',
          width: '38px',
          placeItems: 'center',
          borderRadius: '13px',
          background: 'var(--accent)',
          color: 'white',
        },
        '.sidebar-nav': {
          height: 'calc(100vh - 67px)',
          overflowY: 'auto',
          padding: '10px 9px 20px',
          scrollbarWidth: 'thin',
        },
        '.sidebar-group': { marginBottom: '10px' },
        '.sidebar-group > p': {
          margin: '0 10px 4px',
          color: 'var(--text-muted)',
          fontSize: '9px',
          fontWeight: '600',
          textTransform: 'uppercase',
        },
        '.sidebar-link': {
          display: 'flex',
          minHeight: '34px',
          alignItems: 'center',
          gap: '9px',
          border: '1px solid transparent',
          borderRadius: '999px',
          padding: '6px 11px',
          color: 'var(--text-muted)',
          fontSize: '11px',
          fontWeight: '500',
          textDecoration: 'none',
          transition: '.15s ease',
        },
        '.sidebar-link:hover': {
          background: 'var(--surface-hover)',
          color: 'var(--text)',
        },
        '.sidebar-link.active': {
          background: 'var(--accent-soft)',
          color: 'var(--accent-soft-text)',
        },
        '.admin-bar': {
          position: 'relative',
          zIndex: '30',
          display: 'flex',
          minHeight: '64px',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '12px',
          border: '0',
          borderBottom: cardBorder,
          borderRadius: '0',
          background: 'var(--surface)',
          margin: '0 -20px',
          padding: '0 20px',
        },
        '.admin-bar strong, .admin-bar span': { display: 'block' },
        '.admin-bar strong': { fontSize: '14px' },
        '.admin-bar span': { marginTop: '1px', color: 'var(--text-muted)', fontSize: '12px' },
        '.menu-button': {
          display: 'grid',
          height: '39px',
          width: '39px',
          placeItems: 'center',
          border: cardBorder,
          borderRadius: '999px',
          background: 'var(--surface)',
          color: 'var(--text-muted)',
        },
        '.app-menu': {
          position: 'absolute',
          top: '74px',
          right: '15px',
          zIndex: '40',
          display: 'grid',
          width: 'min(92vw, 420px)',
          gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
          gap: '6px',
          border: cardBorder,
          borderRadius: '16px',
          background: 'var(--surface)',
          padding: '10px',
          boxShadow: 'var(--shadow-flyout)',
        },
        '.app-menu-link': {
          display: 'flex',
          minHeight: '38px',
          alignItems: 'center',
          gap: '8px',
          borderRadius: '9px',
          padding: '7px 9px',
          color: 'var(--text-muted)',
          fontSize: '12px',
          fontWeight: '500',
          textDecoration: 'none',
        },
        '.app-menu-link:hover, .app-menu-link.active': {
          background: 'var(--accent-soft)',
          color: 'var(--accent-soft-text)',
        },
        '.app-main': { paddingTop: '14px' },
        '.module-page': { minWidth: '0' },
        '.module-head': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '14px',
        },
        '.module-title': {
          display: 'inline-flex',
          minHeight: '51px',
          alignItems: 'center',
          gap: '12px',
        },
        '.module-title h1': {
          margin: '0',
          fontSize: '24px',
          fontWeight: '600',
          letterSpacing: '0',
        },
        '.module-title span': { color: 'var(--text-muted)', fontSize: '12px', fontWeight: '500' },
        '.round-add': {
          display: 'grid',
          height: '51px',
          width: '51px',
          flex: 'none',
          placeItems: 'center',
          border: '1px solid var(--accent)',
          borderRadius: '999px',
          background: 'var(--accent)',
          color: 'white',
          textDecoration: 'none',
        },
        '.round-add:hover': { background: 'var(--accent-hover)', borderColor: 'var(--accent-hover)' },
        '.module-tools': { display: 'flex', margin: '15px 0', alignItems: 'center', gap: '9px' },
        '.pill-search': {
          display: 'flex',
          width: 'min(100%, 450px)',
          height: '42px',
          alignItems: 'center',
          gap: '8px',
          border: cardBorder,
          borderRadius: '999px',
          background: 'var(--surface)',
          padding: '0 16px',
          color: 'var(--text-muted)',
        },
        '.pill-search input': {
          minWidth: '0',
          flex: '1',
          border: '0',
          background: 'transparent',
          color: 'var(--text)',
          fontSize: '13px',
          outline: '0',
        },
        '.pill-search input::placeholder': { color: 'var(--text-muted)' },
        '.filter-pill': {
          height: '38px',
          border: cardBorder,
          borderRadius: '999px',
          background: 'var(--surface)',
          padding: '0 13px',
          color: 'var(--text-muted)',
          fontSize: '12px',
          outline: '0',
        },
        '.filter-pill:hover': { background: 'var(--surface-hover)' },
        '.searchable-select': { position: 'relative', width: '100%' },
        '.searchable-select-control': {
          display: 'flex',
          height: '41px',
          alignItems: 'center',
          gap: '7px',
          border: cardBorder,
          borderRadius: '10px',
          background: 'var(--surface)',
          padding: '0 10px',
          color: 'var(--text-muted)',
        },
        '.searchable-select-control input': {
          minWidth: '0',
          width: '100%',
          height: '100%',
          border: '0',
          background: 'transparent',
          color: 'var(--text)',
          fontSize: '13px',
          outline: '0',
        },
        '.searchable-select-clear': {
          display: 'grid',
          height: '24px',
          width: '24px',
          flex: 'none',
          placeItems: 'center',
          border: '0',
          borderRadius: '999px',
          background: 'transparent',
          color: 'var(--text-muted)',
        },
        '.searchable-select-menu': {
          position: 'absolute',
          top: 'calc(100% + 5px)',
          right: '0',
          left: '0',
          zIndex: '80',
          maxHeight: '220px',
          overflowY: 'auto',
          border: cardBorder,
          borderRadius: '12px',
          background: 'var(--surface)',
          padding: '5px',
          boxShadow: 'var(--shadow-flyout)',
        },
        '.searchable-select-menu button': {
          display: 'block',
          width: '100%',
          border: '0',
          borderRadius: '7px',
          background: 'transparent',
          padding: '8px 9px',
          color: 'var(--text)',
          textAlign: 'left',
          fontSize: '12px',
        },
        '.searchable-select-menu button:hover, .searchable-select-menu button.selected': {
          background: 'var(--accent-soft)',
          color: 'var(--accent-soft-text)',
        },
        '.searchable-select-empty': {
          display: 'block',
          padding: '9px',
          color: 'var(--text-muted)',
          fontSize: '12px',
        },
        '.glass-table': {
          overflowX: 'auto',
          border: cardBorder,
          borderRadius: 'var(--ui-radius)',
          background: 'var(--surface)',
        },
        '.glass-table table': {
          width: '100%',
          minWidth: '780px',
          borderCollapse: 'collapse',
          fontSize: '13px',
        },
        '.glass-table th': {
          background: 'var(--surface)',
          padding: '14px 16px',
          color: 'var(--text-muted)',
          textAlign: 'left',
          fontSize: '10px',
          fontWeight: '500',
          letterSpacing: '.03em',
          textTransform: 'uppercase',
          borderBottom: cardBorder,
        },
        '.glass-table td': { padding: '14px 16px', color: 'var(--text)', verticalAlign: 'middle' },
        '.glass-table tbody tr': { transition: 'background .15s' },
        '.glass-table tbody tr:hover': { background: 'var(--surface-soft)' },
        '.table-pagination': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '12px',
          padding: '11px 4px',
          color: 'var(--text-muted)',
          fontSize: '11px',
        },
        '.table-pagination > div': { display: 'flex', alignItems: 'center', gap: '8px' },
        '.table-pagination button': {
          display: 'grid',
          height: '30px',
          width: '30px',
          placeItems: 'center',
          border: cardBorder,
          borderRadius: '8px',
          background: 'var(--surface)',
          color: 'var(--text-muted)',
        },
        '.table-pagination button:disabled': { cursor: 'not-allowed', opacity: '.4' },
        '.auto-table-toolbar': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'flex-end',
          margin: '9px 0',
          gap: '8px',
        },
        '.auto-table-search': {
          display: 'flex',
          alignItems: 'center',
          gap: '7px',
          color: 'var(--text-muted)',
          fontSize: '10px',
          fontWeight: '500',
        },
        '.auto-table-search input': {
          width: 'min(100%, 260px)',
          height: '34px',
          border: cardBorder,
          borderRadius: '999px',
          background: 'var(--surface)',
          padding: '0 12px',
          color: 'var(--text)',
          fontSize: '12px',
          outline: '0',
        },
        '.glass-table strong, .glass-table small': { display: 'block' },
        '.glass-table strong': { color: 'var(--text)', fontSize: '13px' },
        '.glass-table small': { marginTop: '2px', color: 'var(--text-muted)', fontSize: '11px' },
        '.row-actions': { display: 'flex', gap: '7px' },
        '.icon-soft': {
          display: 'grid',
          height: '40px',
          width: '42px',
          placeItems: 'center',
          border: '0',
          borderRadius: '8px',
          background: 'transparent',
          color: 'var(--text-muted)',
        },
        '.icon-soft:hover': { background: 'var(--surface-hover)', color: 'var(--text)' },
        '.status': {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '6px',
          borderRadius: '999px',
          padding: '4px 10px',
          fontSize: '12px',
          fontWeight: '500',
          lineHeight: '1.4',
        },
        '.status::before': {
          content: '""',
          width: '6px',
          height: '6px',
          flex: 'none',
          borderRadius: '50%',
          background: 'currentColor',
        },
        '.status-green': {
          background: 'var(--status-green-bg)',
          color: 'var(--status-green-text)',
        },
        '.status-amber': {
          background: 'var(--status-amber-bg)',
          color: 'var(--status-amber-text)',
        },
        '.status-red': {
          background: 'var(--status-red-bg)',
          color: 'var(--status-red-text)',
        },
        '.status-blue': {
          background: 'var(--status-blue-bg)',
          color: 'var(--status-blue-text)',
        },
        '.status:not(.status-green):not(.status-amber):not(.status-red):not(.status-blue)': {
          background: 'var(--status-gray-bg)',
          color: 'var(--status-gray-text)',
        },
        '.modal-backdrop': {
          position: 'fixed',
          inset: '0',
          zIndex: '60',
          display: 'grid',
          placeItems: 'center',
          overflowY: 'auto',
          background: 'var(--scrim)',
          padding: '16px',
          backdropFilter: 'blur(3px)',
        },
        '.operation-screen': {
          display: 'block',
          marginTop: '18px',
          border: cardBorder,
          borderRadius: '18px',
          background: 'var(--surface-soft)',
          padding: '8px',
        },
        '.crud-modal': {
          width: 'min(100%, 690px)',
          maxHeight: 'calc(100vh - 32px)',
          overflowY: 'auto',
          border: cardBorder,
          borderRadius: 'var(--radius-container-lg)',
          background: 'var(--surface)',
        },
        '.modal-top': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          borderBottom: cardBorder,
          padding: '16px 18px',
        },
        '.modal-top h2': { margin: '0', fontSize: '18px' },
        '.modal-close': {
          display: 'grid',
          height: '36px',
          width: '36px',
          placeItems: 'center',
          border: '0',
          borderRadius: '999px',
          background: 'transparent',
          color: 'var(--text-muted)',
        },
        '.modal-close:hover': { background: 'var(--surface-hover)', color: 'var(--text)' },
        '.modal-form': {
          display: 'grid',
          gridTemplateColumns: '1fr',
          gap: '13px',
          padding: '17px 18px',
        },
        '.modal-form label > span': {
          display: 'block',
          margin: '0 0 5px 3px',
          color: 'var(--text-muted)',
          fontSize: '10px',
          fontWeight: '500',
          textTransform: 'uppercase',
        },
        '.modal-form input, .modal-form select, .modal-form textarea': {
          width: '100%',
          border: cardBorder,
          borderRadius: '999px',
          background: 'var(--surface)',
          padding: '9px 13px',
          color: 'var(--text)',
          fontSize: '13px',
          outline: '0',
        },
        '.modal-form input, .modal-form select': { height: '40px' },
        '.modal-form textarea': { minHeight: '78px', borderRadius: '14px', resize: 'vertical' },
        '.modal-form input:focus, .modal-form select:focus, .modal-form textarea:focus': {
          borderColor: 'var(--accent)',
          boxShadow: '0 0 0 3px color-mix(in srgb, var(--accent) 18%, transparent)',
        },
        '.field-wide': { gridColumn: '1 / -1' },
        '.check-field': { display: 'flex', alignItems: 'center', gap: '8px' },
        '.check-field input': {
          height: '18px',
          width: '18px',
          borderRadius: '6px',
          accentColor: 'var(--accent)',
        },
        '.modal-actions': {
          display: 'flex',
          gridColumn: '1 / -1',
          justifyContent: 'flex-end',
          gap: '8px',
          paddingTop: '3px',
        },
        '.btn-primary, .btn-secondary': {
          display: 'inline-flex',
          minHeight: '39px',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '6px',
          borderRadius: '999px',
          padding: '0 16px',
          fontSize: '12px',
          fontWeight: '600',
          textDecoration: 'none',
        },
        '.btn-primary': {
          border: '1px solid var(--accent)',
          background: 'var(--accent)',
          color: 'white',
        },
        '.btn-primary:hover': {
          background: 'var(--accent-hover)',
          borderColor: 'var(--accent-hover)',
        },
        '.btn-secondary': {
          border: cardBorder,
          background: 'var(--surface)',
          color: 'var(--text)',
          fontWeight: '500',
        },
        '.btn-secondary:hover': { background: 'var(--surface-hover)' },
        '.summary-row': {
          display: 'grid',
          gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
          gap: '10px',
          margin: '15px 0',
        },
        '.summary-glass': {
          border: cardBorder,
          borderRadius: 'var(--ui-radius)',
          background: 'var(--surface)',
          padding: '16px',
        },
        '.summary-glass span': {
          color: 'var(--text-muted)',
          fontSize: '10px',
          fontWeight: '500',
          textTransform: 'uppercase',
        },
        '.summary-glass strong': {
          display: 'block',
          marginTop: '7px',
          color: 'var(--text)',
          fontSize: '23px',
          fontWeight: '600',
        },

        '.operation-modal': { width: 'min(100%, 880px)' },
        '.modal-top small': {
          display: 'block',
          marginTop: '3px',
          color: 'var(--text-muted)',
          fontSize: '11px',
        },
        '.operation-form, .operation-detail': { padding: '17px 18px' },
        '.stepper': {
          display: 'grid',
          gridTemplateColumns: 'auto 1fr auto 1fr auto',
          alignItems: 'center',
          gap: '8px',
          marginBottom: '20px',
        },
        '.stepper > span': {
          display: 'grid',
          height: '34px',
          minWidth: '34px',
          placeItems: 'center',
          border: cardBorder,
          borderRadius: '999px',
          background: 'var(--surface)',
          color: 'var(--text-muted)',
          fontSize: '11px',
          fontWeight: '600',
        },
        '.stepper > span small': { display: 'none' },
        '.stepper > span.active': {
          borderColor: 'var(--accent)',
          background: 'var(--accent)',
          color: 'white',
        },
        '.stepper > i': {
          height: '2px',
          borderRadius: '999px',
          background: 'var(--border)',
        },
        '.step-fields': { display: 'grid', gridTemplateColumns: '1fr', gap: '13px' },
        '.step-fields label > span, .product-line label > span, .review-notes > span': {
          display: 'block',
          margin: '0 0 5px 3px',
          color: 'var(--text-muted)',
          fontSize: '10px',
          fontWeight: '500',
          textTransform: 'uppercase',
        },
        '.step-fields input, .step-fields select, .product-line input, .product-line select, .review-notes textarea':
          {
            width: '100%',
            border: cardBorder,
            borderRadius: '10px',
            background: 'var(--surface)',
            padding: '9px 12px',
            color: 'var(--text)',
            fontSize: '13px',
            outline: '0',
          },
        '.step-fields input, .step-fields select, .product-line input, .product-line select': {
          height: '41px',
        },
        '.step-fields input:focus, .step-fields select:focus, .product-line input:focus, .product-line select:focus, .review-notes textarea:focus':
          {
            borderColor: 'var(--accent)',
            boxShadow: '0 0 0 3px color-mix(in srgb, var(--accent) 18%, transparent)',
          },
        '.lines-editor': { minHeight: '250px' },
        '.lines-head': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '12px',
          marginBottom: '11px',
        },
        '.lines-head strong, .lines-head small': { display: 'block' },
        '.lines-head strong': { fontSize: '14px' },
        '.lines-head small': { marginTop: '3px', color: 'var(--text-muted)', fontSize: '11px' },
        '.product-line': {
          display: 'grid',
          gridTemplateColumns: 'minmax(0,1fr) 76px',
          gap: '8px',
          alignItems: 'end',
          marginBottom: '9px',
          border: cardBorder,
          borderRadius: '12px',
          background: 'var(--surface-soft)',
          padding: '10px',
        },
        '.line-product': { gridColumn: '1 / -1' },
        '.line-lote': {
          display: 'flex',
          flexWrap: 'wrap',
          alignItems: 'end',
          gap: '8px',
        },
        '.line-lote > label': { flex: '1 1 160px', minWidth: '0' },
        '.line-lote > button': { flex: 'none', height: '41px' },
        '.line-total': {
          alignSelf: 'center',
          color: 'var(--text)',
          fontSize: '12px',
          textAlign: 'right',
        },
        '.line-remove': {
          display: 'grid',
          height: '38px',
          width: '38px',
          placeItems: 'center',
          border: '0',
          borderRadius: '8px',
          background: 'transparent',
          color: 'var(--status-red-text)',
        },
        '.line-remove:hover': { background: 'var(--surface-hover)' },
        '.line-remove:disabled': { cursor: 'not-allowed', opacity: '.35' },
        '.stock-hint, .stock-warning': {
          display: 'block',
          margin: '4px 0 0 3px',
          fontSize: '10px',
          fontWeight: '500',
        },
        '.stock-hint': { color: 'var(--status-green-text)' },
        '.stock-warning': { color: 'var(--status-red-text)' },
        '.review-step': { display: 'grid', gap: '8px' },
        '.review-route': {
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          marginBottom: '5px',
          border: '1px solid var(--accent)',
          borderRadius: '12px',
          background: 'var(--accent-soft)',
          padding: '11px 13px',
          color: 'var(--accent-soft-text)',
        },
        '.review-route div': { minWidth: '0', flex: '1' },
        '.review-route small, .review-route strong': { display: 'block' },
        '.review-route small': { fontSize: '9px', fontWeight: '600', textTransform: 'uppercase' },
        '.review-route strong': {
          overflow: 'hidden',
          marginTop: '2px',
          color: 'var(--text)',
          fontSize: '13px',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        },
        '.review-route > span': {
          borderRadius: '999px',
          background: 'var(--surface)',
          padding: '5px 8px',
          color: 'var(--text-muted)',
          fontSize: '10px',
          fontWeight: '500',
        },
        '.detail-line': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '15px',
          borderBottom: cardBorder,
          padding: '9px 4px',
          fontSize: '12px',
        },
        '.detail-line span': { minWidth: '0', color: 'var(--text)', fontWeight: '500' },
        '.detail-line small': {
          display: 'block',
          marginTop: '3px',
          color: 'var(--text-muted)',
          fontSize: '10px',
          fontWeight: '400',
        },
        '.detail-line > strong': { flex: 'none' },
        '.review-notes': { display: 'block', marginTop: '8px' },
        '.review-notes textarea': { minHeight: '65px', resize: 'vertical' },
        '.totals-box': {
          display: 'grid',
          gap: '6px',
          marginTop: '5px',
          borderRadius: '12px',
          background: 'var(--surface-soft)',
          padding: '11px 13px',
        },
        '.totals-box span': {
          display: 'flex',
          justifyContent: 'space-between',
          color: 'var(--text-muted)',
          fontSize: '11px',
        },
        '.totals-box .grand-total': {
          borderTop: cardBorder,
          paddingTop: '8px',
          color: 'var(--text)',
          fontSize: '14px',
          fontWeight: '600',
        },
        '.auto-note': {
          display: 'flex',
          alignItems: 'center',
          gap: '7px',
          margin: '4px 0 0',
          borderRadius: '9px',
          background: 'var(--status-green-bg)',
          padding: '9px 11px',
          color: 'var(--status-green-text)',
          fontSize: '11px',
          fontWeight: '500',
        },
        '.wizard-actions': {
          display: 'flex',
          flexWrap: 'wrap',
          justifyContent: 'space-between',
          gap: '8px',
          marginTop: '18px',
          borderTop: cardBorder,
          paddingTop: '13px',
        },
        '.wizard-actions > :last-child': { marginLeft: 'auto' },
        '.notice-error': {
          margin: '12px 0',
          border: '1px solid var(--status-red-text)',
          borderRadius: '9px',
          background: 'var(--status-red-bg)',
          padding: '9px 12px',
          color: 'var(--status-red-text)',
          fontSize: '11px',
          fontWeight: '500',
        },
        '.confirm-soft': {
          display: 'inline-flex',
          height: '40px',
          alignItems: 'center',
          gap: '5px',
          border: '1px solid var(--status-green-text)',
          borderRadius: '8px',
          background: 'var(--status-green-bg)',
          padding: '0 10px',
          color: 'var(--status-green-text)',
          fontSize: '11px',
          fontWeight: '500',
        },
        '.kardex-link': {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '4px',
          color: 'var(--accent)',
          fontSize: '11px',
          fontWeight: '500',
          textDecoration: 'none',
        },
        '.detail-summary': {
          display: 'grid',
          gridTemplateColumns: '1fr',
          gap: '8px',
          marginBottom: '10px',
        },
        '.detail-summary span': {
          border: cardBorder,
          borderRadius: '10px',
          background: 'var(--surface-soft)',
          padding: '9px',
          color: 'var(--text-muted)',
          fontSize: '9px',
          fontWeight: '500',
          textTransform: 'uppercase',
        },
        '.detail-summary strong': {
          display: 'block',
          marginTop: '4px',
          color: 'var(--text)',
          fontSize: '12px',
          textTransform: 'none',
        },
        '.review-total': {
          display: 'flex',
          justifyContent: 'space-between',
          marginTop: '8px',
          borderRadius: '10px',
          background: 'var(--surface-soft)',
          padding: '12px',
          fontSize: '15px',
          fontWeight: '600',
        },
        '.inventory-flow': {
          display: 'grid',
          gridTemplateColumns: '1fr',
          gap: '8px',
          marginTop: '13px',
        },
        '.inventory-flow > div': {
          display: 'flex',
          alignItems: 'center',
          gap: '9px',
          border: cardBorder,
          borderRadius: '12px',
          background: 'var(--surface-soft)',
          padding: '10px 12px',
          color: 'var(--accent-soft-text)',
        },
        '.inventory-flow span, .inventory-flow strong': { display: 'block' },
        '.inventory-flow span': { color: 'var(--text-muted)', fontSize: '10px' },
        '.inventory-flow strong': { marginTop: '2px', color: 'var(--text)', fontSize: '12px' },
        '.inventory-flow > i': { display: 'none' },
        '.kardex-detail-line': {
          display: 'grid',
          gridTemplateColumns: 'minmax(0,1fr) auto auto auto',
          alignItems: 'center',
          gap: '12px',
          borderBottom: cardBorder,
          padding: '11px 3px',
        },
        '.kardex-detail-line > span': { fontSize: '12px', fontWeight: '600' },
        '.kardex-detail-line small': {
          display: 'block',
          color: 'var(--text-muted)',
          fontSize: '9px',
          fontWeight: '400',
        },
        '.kardex-detail-line div': { textAlign: 'right' },
        '.kardex-detail-line div strong': { display: 'block', fontSize: '13px' },
        '.panel, .form-crud': {
          border: cardBorder,
          borderRadius: 'var(--ui-radius)',
          background: 'var(--surface)',
        },
        '.table-wrap': {
          overflowX: 'auto',
          border: cardBorder,
          borderRadius: 'var(--ui-radius)',
          background: 'var(--surface)',
        },
        '.table': {
          width: '100%',
          minWidth: '760px',
          borderCollapse: 'collapse',
          fontSize: '13px',
        },
        '.table th': {
          background: 'var(--surface)',
          padding: '14px',
          textAlign: 'left',
          borderBottom: cardBorder,
        },
        '.table td': { padding: '10px 14px' },
        '.control, .input-control': {
          width: '100%',
          border: cardBorder,
          borderRadius: '999px',
          background: 'var(--surface)',
          padding: '8px 12px',
          color: 'var(--text)',
          outline: '0',
        },
        '.label': {
          color: 'var(--text-muted)',
          fontSize: '10px',
          fontWeight: '500',
          textTransform: 'uppercase',
        },
        '.btn-circular': {
          display: 'grid',
          height: '50px',
          width: '50px',
          placeItems: 'center',
          borderRadius: '999px',
          background: 'var(--accent)',
          color: 'white',
        },
        '@media (min-width: 640px)': {
          '.app-shell': { paddingLeft: '5px', paddingRight: '10px' },
          '.app-menu': { gridTemplateColumns: 'repeat(3,minmax(0,1fr))', width: '570px' },
          '.modal-form': { gridTemplateColumns: 'repeat(2,minmax(0,1fr))' },
          '.summary-row': { gridTemplateColumns: 'repeat(4,minmax(0,1fr))' },
          '.stepper > span': { display: 'flex', minWidth: '105px', gap: '6px', padding: '0 12px' },
          '.stepper > span small': { display: 'inline', fontSize: '10px' },
          '.step-fields': { gridTemplateColumns: 'repeat(2,minmax(0,1fr))' },
          '.product-line': {
            gridTemplateColumns:
              'minmax(210px,1.7fr) minmax(85px,.55fr) minmax(105px,.7fr) 85px 38px',
          },
          '.line-product': { gridColumn: 'auto' },
          '.detail-summary': { gridTemplateColumns: 'repeat(3,minmax(0,1fr))' },
          '.inventory-flow': { gridTemplateColumns: '1fr auto 1fr auto 1fr', alignItems: 'center' },
          '.inventory-flow > i': {
            display: 'block',
            width: '20px',
            height: '2px',
            background: 'var(--border)',
          },
        },
        '@media (min-width: 1024px)': {
          '.app-shell': { paddingLeft: '246px' },
          '.desktop-sidebar': { display: 'block' },
          '.menu-button, .app-menu': { display: 'none' },
        },
      });
    }),
  ],
};

export default config;
