import type { Config } from 'tailwindcss';
import plugin from 'tailwindcss/plugin';

const glassBorder = '1px solid rgba(255,255,255,.76)';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        ink: '#15213a',
        brand: { 500: '#2563eb', 600: '#1d4ed8' },
      },
    },
  },
  plugins: [
    plugin(({ addBase, addComponents }) => {
      addBase({
        body: {
          margin: '0',
          minHeight: '100vh',
          background: 'linear-gradient(120deg, #fff0cf 0%, #e2e8ff 34%, #b8e7fb 100%)',
          backgroundAttachment: 'fixed',
          color: '#15213a',
        },
        'button, input, select, textarea': { font: 'inherit' },
        button: { cursor: 'pointer' },
      });

      addComponents({
        '.app-shell': { minHeight: '100vh', padding: '5px 7px 30px' },
        '.desktop-sidebar': {
          position: 'fixed',
          inset: '5px auto 5px 5px',
          zIndex: '35',
          display: 'none',
          width: '232px',
          overflow: 'hidden',
          border: glassBorder,
          borderRadius: '27px',
          background: 'rgba(255,255,255,.25)',
          boxShadow: '0 12px 38px rgba(63,84,125,.08)',
          backdropFilter: 'blur(16px)',
        },
        '.sidebar-brand': {
          display: 'flex',
          minHeight: '67px',
          alignItems: 'center',
          gap: '10px',
          borderBottom: '1px solid rgba(255,255,255,.66)',
          padding: '0 15px',
        },
        '.sidebar-brand strong, .sidebar-brand small': { display: 'block' },
        '.sidebar-brand strong': {
          color: '#182841',
          fontSize: '13px',
          fontWeight: '900',
          textTransform: 'uppercase',
        },
        '.sidebar-brand small': { marginTop: '2px', color: '#5b7190', fontSize: '10px' },
        '.sidebar-logo': {
          display: 'grid',
          height: '38px',
          width: '38px',
          placeItems: 'center',
          borderRadius: '13px',
          background: '#2563eb',
          color: 'white',
          boxShadow: '0 5px 11px rgba(37,99,235,.18)',
        },
        '.sidebar-nav': {
          height: 'calc(100vh - 77px)',
          overflowY: 'auto',
          padding: '10px 9px 20px',
          scrollbarWidth: 'thin',
        },
        '.sidebar-group': { marginBottom: '10px' },
        '.sidebar-group > p': {
          margin: '0 10px 4px',
          color: '#7083a0',
          fontSize: '9px',
          fontWeight: '900',
          textTransform: 'uppercase',
        },
        '.sidebar-link': {
          display: 'flex',
          minHeight: '34px',
          alignItems: 'center',
          gap: '9px',
          border: '1px solid transparent',
          borderRadius: '999px',
          padding: '6px 11px',
          color: '#405876',
          fontSize: '11px',
          fontWeight: '750',
          textDecoration: 'none',
          transition: '.15s ease',
        },
        '.sidebar-link:hover': {
          borderColor: 'rgba(255,255,255,.74)',
          background: 'rgba(255,255,255,.28)',
          color: '#2757d8',
        },
        '.sidebar-link.active': {
          borderColor: 'rgba(111,153,255,.40)',
          background: '#2563eb',
          color: 'white',
          boxShadow: '0 4px 10px rgba(37,99,235,.16)',
        },
        '.admin-bar': {
          position: 'relative',
          zIndex: '30',
          display: 'flex',
          minHeight: '64px',
          alignItems: 'center',
          justifyContent: 'space-between',
          border: glassBorder,
          borderRadius: '999px',
          background: 'rgba(255,255,255,.28)',
          padding: '0 18px 0 25px',
          backdropFilter: 'blur(12px)',
        },
        '.admin-bar strong, .admin-bar span': { display: 'block' },
        '.admin-bar strong': { fontSize: '14px' },
        '.admin-bar span': { marginTop: '1px', color: '#3b65ed', fontSize: '12px' },
        '.menu-button': {
          display: 'grid',
          height: '39px',
          width: '39px',
          placeItems: 'center',
          border: '1px solid rgba(255,255,255,.72)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.34)',
          color: '#34506d',
        },
        '.app-menu': {
          position: 'absolute',
          top: '74px',
          right: '15px',
          zIndex: '40',
          display: 'grid',
          width: 'min(92vw, 420px)',
          gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
          gap: '6px',
          border: '1px solid rgba(255,255,255,.82)',
          borderRadius: '16px',
          background: 'rgba(248,251,255,.92)',
          padding: '10px',
          boxShadow: '0 18px 45px rgba(58,77,113,.18)',
          backdropFilter: 'blur(18px)',
        },
        '.app-menu-link': {
          display: 'flex',
          minHeight: '38px',
          alignItems: 'center',
          gap: '8px',
          borderRadius: '9px',
          padding: '7px 9px',
          color: '#41536f',
          fontSize: '12px',
          fontWeight: '700',
          textDecoration: 'none',
        },
        '.app-menu-link:hover, .app-menu-link.active': { background: '#e5edff', color: '#2352d6' },
        '.app-main': { paddingTop: '14px' },
        '.module-page': { minWidth: '0' },
        '.module-head': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '14px',
        },
        '.module-title': {
          display: 'inline-flex',
          minHeight: '51px',
          alignItems: 'center',
          gap: '12px',
          border: '1px solid rgba(255,255,255,.72)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.30)',
          padding: '7px 17px',
        },
        '.module-title h1': {
          margin: '0',
          fontSize: '24px',
          fontWeight: '900',
          letterSpacing: '0',
        },
        '.module-title span': { color: '#4b6484', fontSize: '12px', fontWeight: '700' },
        '.round-add': {
          display: 'grid',
          height: '51px',
          width: '51px',
          flex: 'none',
          placeItems: 'center',
          border: '1px solid #5e8bf4',
          borderRadius: '999px',
          background: '#2563eb',
          color: 'white',
          textDecoration: 'none',
          boxShadow: '0 4px 9px rgba(37,99,235,.16)',
        },
        '.round-add:hover': { background: '#1d4ed8', transform: 'scale(1.04)' },
        '.module-tools': { display: 'flex', margin: '15px 0', alignItems: 'center', gap: '9px' },
        '.pill-search': {
          display: 'flex',
          width: 'min(100%, 450px)',
          height: '42px',
          alignItems: 'center',
          gap: '8px',
          border: '1px solid rgba(255,255,255,.75)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.38)',
          padding: '0 16px',
          color: '#334155',
        },
        '.pill-search input': {
          minWidth: '0',
          flex: '1',
          border: '0',
          background: 'transparent',
          color: '#15213a',
          fontSize: '13px',
          outline: '0',
        },
        '.pill-search input::placeholder': { color: '#8290ab' },
        '.filter-pill': {
          height: '38px',
          border: '1px solid rgba(255,255,255,.72)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.33)',
          padding: '0 13px',
          color: '#4b5f7c',
          fontSize: '12px',
          outline: '0',
        },
        '.searchable-select': { position: 'relative', width: '100%' },
        '.searchable-select-control': {
          display: 'flex',
          height: '41px',
          alignItems: 'center',
          gap: '7px',
          border: '1px solid rgba(255,255,255,.9)',
          borderRadius: '10px',
          background: 'rgba(255,255,255,.55)',
          padding: '0 10px',
          color: '#6b7e98',
        },
        '.searchable-select-control input': {
          minWidth: '0',
          width: '100%',
          height: '100%',
          border: '0',
          background: 'transparent',
          color: '#20334f',
          fontSize: '13px',
          outline: '0',
        },
        '.searchable-select-clear': {
          display: 'grid',
          height: '24px',
          width: '24px',
          flex: 'none',
          placeItems: 'center',
          border: '0',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.55)',
          color: '#627590',
        },
        '.searchable-select-menu': {
          position: 'absolute',
          top: 'calc(100% + 5px)',
          right: '0',
          left: '0',
          zIndex: '80',
          maxHeight: '220px',
          overflowY: 'auto',
          border: '1px solid rgba(255,255,255,.95)',
          borderRadius: '10px',
          background: 'rgba(248,251,255,.98)',
          padding: '5px',
          boxShadow: '0 15px 35px rgba(42,61,97,.18)',
        },
        '.searchable-select-menu button': {
          display: 'block',
          width: '100%',
          border: '0',
          borderRadius: '7px',
          background: 'transparent',
          padding: '8px 9px',
          color: '#263b58',
          textAlign: 'left',
          fontSize: '12px',
        },
        '.searchable-select-menu button:hover, .searchable-select-menu button.selected': {
          background: '#e5edff',
          color: '#2352d6',
        },
        '.searchable-select-empty': {
          display: 'block',
          padding: '9px',
          color: '#71829a',
          fontSize: '12px',
        },
        '.glass-table': {
          overflowX: 'auto',
          border: glassBorder,
          borderRadius: '17px',
          background: 'rgba(255,255,255,.22)',
        },
        '.glass-table table': {
          width: '100%',
          minWidth: '780px',
          borderCollapse: 'collapse',
          fontSize: '13px',
        },
        '.glass-table th': {
          background: 'rgba(255,255,255,.20)',
          padding: '16px 13px',
          color: '#526a8d',
          textAlign: 'left',
          fontSize: '10px',
          fontWeight: '850',
          textTransform: 'uppercase',
        },
        '.glass-table td': { padding: '9px 13px', color: '#233653', verticalAlign: 'middle' },
        '.glass-table tbody tr': { transition: 'background .15s' },
        '.glass-table tbody tr:hover': { background: 'rgba(255,255,255,.24)' },
        '.table-pagination': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '12px',
          padding: '11px 4px',
          color: '#607594',
          fontSize: '11px',
        },
        '.table-pagination > div': { display: 'flex', alignItems: 'center', gap: '8px' },
        '.table-pagination button': {
          display: 'grid',
          height: '30px',
          width: '30px',
          placeItems: 'center',
          border: glassBorder,
          borderRadius: '8px',
          background: 'rgba(255,255,255,.38)',
          color: '#34506d',
        },
        '.table-pagination button:disabled': { cursor: 'not-allowed', opacity: '.4' },
        '.auto-table-toolbar': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'flex-end',
          margin: '9px 0',
          gap: '8px',
        },
        '.auto-table-search': {
          display: 'flex',
          alignItems: 'center',
          gap: '7px',
          color: '#607594',
          fontSize: '10px',
          fontWeight: '800',
        },
        '.auto-table-search input': {
          width: 'min(100%, 260px)',
          height: '34px',
          border: '1px solid rgba(255,255,255,.75)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.34)',
          padding: '0 12px',
          color: '#20334f',
          fontSize: '12px',
          outline: '0',
        },
        '.glass-table strong, .glass-table small': { display: 'block' },
        '.glass-table strong': { color: '#182841', fontSize: '13px' },
        '.glass-table small': { marginTop: '2px', color: '#587092', fontSize: '11px' },
        '.row-actions': { display: 'flex', gap: '7px' },
        '.icon-soft': {
          display: 'grid',
          height: '40px',
          width: '42px',
          placeItems: 'center',
          border: glassBorder,
          borderRadius: '8px',
          background: 'rgba(255,255,255,.34)',
          color: '#27425f',
        },
        '.icon-soft:hover': { background: 'rgba(255,255,255,.58)' },
        '.status': {
          display: 'inline-flex',
          borderRadius: '6px',
          padding: '4px 8px',
          fontSize: '11px',
          fontWeight: '800',
        },
        '.status-green': {
          background: '#ecfdf5',
          color: '#008a55',
          boxShadow: 'inset 0 0 0 1px #9cf1c8',
        },
        '.status-amber': {
          background: '#fff8df',
          color: '#a46708',
          boxShadow: 'inset 0 0 0 1px #f7d776',
        },
        '.status-red': {
          background: '#fff0f2',
          color: '#c62f4a',
          boxShadow: 'inset 0 0 0 1px #f3a7b3',
        },
        '.status-blue': {
          background: '#eff6ff',
          color: '#2563eb',
          boxShadow: 'inset 0 0 0 1px #a9c8ff',
        },
        '.modal-backdrop': {
          position: 'fixed',
          inset: '0',
          zIndex: '60',
          display: 'grid',
          placeItems: 'center',
          overflowY: 'auto',
          background: 'rgba(31,47,78,.38)',
          padding: '16px',
          backdropFilter: 'blur(3px)',
        },
        '.operation-screen': {
          display: 'block',
          marginTop: '18px',
          border: '1px solid rgba(255,255,255,.76)',
          borderRadius: '18px',
          background: 'rgba(245,249,255,.45)',
          boxShadow: '0 12px 38px rgba(63,84,125,.08)',
          padding: '8px',
        },
        '.crud-modal': {
          width: 'min(100%, 690px)',
          maxHeight: 'calc(100vh - 32px)',
          overflowY: 'auto',
          border: '1px solid rgba(255,255,255,.92)',
          borderRadius: '18px',
          background: 'rgba(245,249,255,.90)',
          boxShadow: '0 22px 60px rgba(42,61,97,.24)',
          backdropFilter: 'blur(22px)',
        },
        '.modal-top': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          borderBottom: '1px solid rgba(255,255,255,.88)',
          padding: '16px 18px',
        },
        '.modal-top h2': { margin: '0', fontSize: '18px' },
        '.modal-close': {
          display: 'grid',
          height: '36px',
          width: '36px',
          placeItems: 'center',
          border: '1px solid rgba(255,255,255,.88)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.45)',
          color: '#3e5674',
        },
        '.modal-form': {
          display: 'grid',
          gridTemplateColumns: '1fr',
          gap: '13px',
          padding: '17px 18px',
        },
        '.modal-form label > span': {
          display: 'block',
          margin: '0 0 5px 3px',
          color: '#536a89',
          fontSize: '10px',
          fontWeight: '850',
          textTransform: 'uppercase',
        },
        '.modal-form input, .modal-form select, .modal-form textarea': {
          width: '100%',
          border: '1px solid rgba(255,255,255,.9)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.55)',
          padding: '9px 13px',
          color: '#20334f',
          fontSize: '13px',
          outline: '0',
        },
        '.modal-form input, .modal-form select': { height: '40px' },
        '.modal-form textarea': { minHeight: '78px', borderRadius: '14px', resize: 'vertical' },
        '.modal-form input:focus, .modal-form select:focus, .modal-form textarea:focus': {
          boxShadow: '0 0 0 2px rgba(37,99,235,.16)',
        },
        '.field-wide': { gridColumn: '1 / -1' },
        '.check-field': { display: 'flex', alignItems: 'center', gap: '8px' },
        '.check-field input': { height: '18px', width: '18px', accentColor: '#2563eb' },
        '.modal-actions': {
          display: 'flex',
          gridColumn: '1 / -1',
          justifyContent: 'flex-end',
          gap: '8px',
          paddingTop: '3px',
        },
        '.btn-primary, .btn-secondary': {
          display: 'inline-flex',
          minHeight: '39px',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '6px',
          borderRadius: '999px',
          padding: '0 16px',
          fontSize: '12px',
          fontWeight: '800',
          textDecoration: 'none',
        },
        '.btn-primary': { border: '1px solid #5b86ed', background: '#2563eb', color: 'white' },
        '.btn-secondary': {
          border: '1px solid rgba(255,255,255,.9)',
          background: 'rgba(255,255,255,.42)',
          color: '#415772',
        },
        '.summary-row': {
          display: 'grid',
          gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
          gap: '10px',
          margin: '15px 0',
        },
        '.summary-glass': {
          border: glassBorder,
          borderRadius: '16px',
          background: 'rgba(255,255,255,.25)',
          padding: '14px',
        },
        '.summary-glass span': {
          color: '#56708e',
          fontSize: '10px',
          fontWeight: '850',
          textTransform: 'uppercase',
        },
        '.summary-glass strong': { display: 'block', marginTop: '7px', fontSize: '23px' },

        '.operation-modal': { width: 'min(100%, 880px)' },
        '.modal-top small': {
          display: 'block',
          marginTop: '3px',
          color: '#6a7d98',
          fontSize: '11px',
        },
        '.operation-form, .operation-detail': { padding: '17px 18px' },
        '.stepper': {
          display: 'grid',
          gridTemplateColumns: 'auto 1fr auto 1fr auto',
          alignItems: 'center',
          gap: '8px',
          marginBottom: '20px',
        },
        '.stepper > span': {
          display: 'grid',
          height: '34px',
          minWidth: '34px',
          placeItems: 'center',
          border: '1px solid rgba(255,255,255,.9)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.43)',
          color: '#687b96',
          fontSize: '11px',
          fontWeight: '900',
        },
        '.stepper > span small': { display: 'none' },
        '.stepper > span.active': { borderColor: '#78a0fb', background: '#2563eb', color: 'white' },
        '.stepper > i': {
          height: '2px',
          borderRadius: '999px',
          background: 'rgba(105,130,170,.22)',
        },
        '.step-fields': { display: 'grid', gridTemplateColumns: '1fr', gap: '13px' },
        '.step-fields label > span, .product-line label > span, .review-notes > span': {
          display: 'block',
          margin: '0 0 5px 3px',
          color: '#536a89',
          fontSize: '10px',
          fontWeight: '850',
          textTransform: 'uppercase',
        },
        '.step-fields input, .step-fields select, .product-line input, .product-line select, .review-notes textarea':
          {
            width: '100%',
            border: '1px solid rgba(255,255,255,.9)',
            borderRadius: '10px',
            background: 'rgba(255,255,255,.55)',
            padding: '9px 12px',
            color: '#20334f',
            fontSize: '13px',
            outline: '0',
          },
        '.step-fields input, .step-fields select, .product-line input, .product-line select': {
          height: '41px',
        },
        '.step-fields input:focus, .step-fields select:focus, .product-line input:focus, .product-line select:focus, .review-notes textarea:focus':
          { boxShadow: '0 0 0 2px rgba(37,99,235,.16)' },
        '.lines-editor': { minHeight: '250px' },
        '.lines-head': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '12px',
          marginBottom: '11px',
        },
        '.lines-head strong, .lines-head small': { display: 'block' },
        '.lines-head strong': { fontSize: '14px' },
        '.lines-head small': { marginTop: '3px', color: '#657b98', fontSize: '11px' },
        '.product-line': {
          display: 'grid',
          gridTemplateColumns: 'minmax(0,1fr) 76px',
          gap: '8px',
          alignItems: 'end',
          marginBottom: '9px',
          border: glassBorder,
          borderRadius: '12px',
          background: 'rgba(255,255,255,.22)',
          padding: '10px',
        },
        '.line-product': { gridColumn: '1 / -1' },
        '.line-total': {
          alignSelf: 'center',
          color: '#1b3150',
          fontSize: '12px',
          textAlign: 'right',
        },
        '.line-remove': {
          display: 'grid',
          height: '38px',
          width: '38px',
          placeItems: 'center',
          border: glassBorder,
          borderRadius: '8px',
          background: 'rgba(255,255,255,.35)',
          color: '#b33a50',
        },
        '.line-remove:disabled': { cursor: 'not-allowed', opacity: '.35' },
        '.stock-hint, .stock-warning': {
          display: 'block',
          margin: '4px 0 0 3px',
          fontSize: '10px',
          fontWeight: '800',
        },
        '.stock-hint': { color: '#16835a' },
        '.stock-warning': { color: '#c23c50' },
        '.review-step': { display: 'grid', gap: '8px' },
        '.review-route': {
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          marginBottom: '5px',
          border: '1px solid rgba(130,170,255,.48)',
          borderRadius: '12px',
          background: 'rgba(226,237,255,.52)',
          padding: '11px 13px',
          color: '#2457d7',
        },
        '.review-route div': { minWidth: '0', flex: '1' },
        '.review-route small, .review-route strong': { display: 'block' },
        '.review-route small': { fontSize: '9px', fontWeight: '800', textTransform: 'uppercase' },
        '.review-route strong': {
          overflow: 'hidden',
          marginTop: '2px',
          color: '#1d3150',
          fontSize: '13px',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
        },
        '.review-route > span': {
          borderRadius: '999px',
          background: 'rgba(255,255,255,.6)',
          padding: '5px 8px',
          color: '#55708f',
          fontSize: '10px',
          fontWeight: '800',
        },
        '.detail-line': {
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '15px',
          borderBottom: '1px solid rgba(255,255,255,.72)',
          padding: '9px 4px',
          fontSize: '12px',
        },
        '.detail-line span': { minWidth: '0', color: '#263b58', fontWeight: '750' },
        '.detail-line small': {
          display: 'block',
          marginTop: '3px',
          color: '#6b7e98',
          fontSize: '10px',
          fontWeight: '600',
        },
        '.detail-line > strong': { flex: 'none' },
        '.review-notes': { display: 'block', marginTop: '8px' },
        '.review-notes textarea': { minHeight: '65px', resize: 'vertical' },
        '.totals-box': {
          display: 'grid',
          gap: '6px',
          marginTop: '5px',
          borderRadius: '12px',
          background: 'rgba(255,255,255,.35)',
          padding: '11px 13px',
        },
        '.totals-box span': {
          display: 'flex',
          justifyContent: 'space-between',
          color: '#61738f',
          fontSize: '11px',
        },
        '.totals-box .grand-total': {
          borderTop: '1px solid rgba(255,255,255,.8)',
          paddingTop: '8px',
          color: '#182c48',
          fontSize: '14px',
          fontWeight: '850',
        },
        '.auto-note': {
          display: 'flex',
          alignItems: 'center',
          gap: '7px',
          margin: '4px 0 0',
          borderRadius: '9px',
          background: 'rgba(223,250,238,.65)',
          padding: '9px 11px',
          color: '#08784d',
          fontSize: '11px',
          fontWeight: '750',
        },
        '.wizard-actions': {
          display: 'flex',
          flexWrap: 'wrap',
          justifyContent: 'space-between',
          gap: '8px',
          marginTop: '18px',
          borderTop: '1px solid rgba(255,255,255,.78)',
          paddingTop: '13px',
        },
        '.wizard-actions > :last-child': { marginLeft: 'auto' },
        '.notice-error': {
          margin: '12px 0',
          border: '1px solid #f3a7b3',
          borderRadius: '9px',
          background: 'rgba(255,240,242,.82)',
          padding: '9px 12px',
          color: '#b4233e',
          fontSize: '11px',
          fontWeight: '750',
        },
        '.confirm-soft': {
          display: 'inline-flex',
          height: '40px',
          alignItems: 'center',
          gap: '5px',
          border: '1px solid #9be9c4',
          borderRadius: '8px',
          background: '#ecfdf5',
          padding: '0 10px',
          color: '#087b50',
          fontSize: '11px',
          fontWeight: '850',
        },
        '.kardex-link': {
          display: 'inline-flex',
          alignItems: 'center',
          gap: '4px',
          color: '#2458df',
          fontSize: '11px',
          fontWeight: '850',
          textDecoration: 'none',
        },
        '.detail-summary': {
          display: 'grid',
          gridTemplateColumns: '1fr',
          gap: '8px',
          marginBottom: '10px',
        },
        '.detail-summary span': {
          border: glassBorder,
          borderRadius: '10px',
          background: 'rgba(255,255,255,.3)',
          padding: '9px',
          color: '#657892',
          fontSize: '9px',
          fontWeight: '800',
          textTransform: 'uppercase',
        },
        '.detail-summary strong': {
          display: 'block',
          marginTop: '4px',
          color: '#1e334f',
          fontSize: '12px',
          textTransform: 'none',
        },
        '.review-total': {
          display: 'flex',
          justifyContent: 'space-between',
          marginTop: '8px',
          borderRadius: '10px',
          background: 'rgba(255,255,255,.36)',
          padding: '12px',
          fontSize: '15px',
          fontWeight: '900',
        },
        '.inventory-flow': {
          display: 'grid',
          gridTemplateColumns: '1fr',
          gap: '8px',
          marginTop: '13px',
        },
        '.inventory-flow > div': {
          display: 'flex',
          alignItems: 'center',
          gap: '9px',
          border: glassBorder,
          borderRadius: '12px',
          background: 'rgba(255,255,255,.22)',
          padding: '10px 12px',
          color: '#315ad0',
        },
        '.inventory-flow span, .inventory-flow strong': { display: 'block' },
        '.inventory-flow span': { color: '#627590', fontSize: '10px' },
        '.inventory-flow strong': { marginTop: '2px', color: '#1e334f', fontSize: '12px' },
        '.inventory-flow > i': { display: 'none' },
        '.kardex-detail-line': {
          display: 'grid',
          gridTemplateColumns: 'minmax(0,1fr) auto auto auto',
          alignItems: 'center',
          gap: '12px',
          borderBottom: '1px solid rgba(255,255,255,.75)',
          padding: '11px 3px',
        },
        '.kardex-detail-line > span': { fontSize: '12px', fontWeight: '800' },
        '.kardex-detail-line small': {
          display: 'block',
          color: '#6a7d97',
          fontSize: '9px',
          fontWeight: '650',
        },
        '.kardex-detail-line div': { textAlign: 'right' },
        '.kardex-detail-line div strong': { display: 'block', fontSize: '13px' },
        '.panel, .form-crud': {
          border: '1px solid rgba(255,255,255,.72)',
          borderRadius: '16px',
          background: 'rgba(255,255,255,.26)',
        },
        '.table-wrap': {
          overflowX: 'auto',
          border: glassBorder,
          borderRadius: '16px',
          background: 'rgba(255,255,255,.22)',
        },
        '.table': {
          width: '100%',
          minWidth: '760px',
          borderCollapse: 'collapse',
          fontSize: '13px',
        },
        '.table th': { background: 'rgba(255,255,255,.2)', padding: '14px', textAlign: 'left' },
        '.table td': { padding: '10px 14px' },
        '.control, .input-control': {
          width: '100%',
          border: '1px solid rgba(255,255,255,.8)',
          borderRadius: '999px',
          background: 'rgba(255,255,255,.42)',
          padding: '8px 12px',
          outline: '0',
        },
        '.label': {
          color: '#5d7190',
          fontSize: '10px',
          fontWeight: '800',
          textTransform: 'uppercase',
        },
        '.btn-circular': {
          display: 'grid',
          height: '50px',
          width: '50px',
          placeItems: 'center',
          borderRadius: '999px',
          background: '#2563eb',
          color: 'white',
        },
        '@media (min-width: 640px)': {
          '.app-shell': { paddingLeft: '5px', paddingRight: '10px' },
          '.app-menu': { gridTemplateColumns: 'repeat(3,minmax(0,1fr))', width: '570px' },
          '.modal-form': { gridTemplateColumns: 'repeat(2,minmax(0,1fr))' },
          '.summary-row': { gridTemplateColumns: 'repeat(4,minmax(0,1fr))' },
          '.stepper > span': { display: 'flex', minWidth: '105px', gap: '6px', padding: '0 12px' },
          '.stepper > span small': { display: 'inline', fontSize: '10px' },
          '.step-fields': { gridTemplateColumns: 'repeat(2,minmax(0,1fr))' },
          '.product-line': {
            gridTemplateColumns:
              'minmax(210px,1.7fr) minmax(85px,.55fr) minmax(105px,.7fr) 85px 38px',
          },
          '.line-product': { gridColumn: 'auto' },
          '.detail-summary': { gridTemplateColumns: 'repeat(3,minmax(0,1fr))' },
          '.inventory-flow': { gridTemplateColumns: '1fr auto 1fr auto 1fr', alignItems: 'center' },
          '.inventory-flow > i': {
            display: 'block',
            width: '20px',
            height: '2px',
            background: 'rgba(75,103,148,.25)',
          },
        },
        '@media (min-width: 1024px)': {
          '.app-shell': { paddingLeft: '246px' },
          '.desktop-sidebar': { display: 'block' },
          '.menu-button, .app-menu': { display: 'none' },
        },
      });
    }),
  ],
};

export default config;
